version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=spy
      - POSTGRES_USER=spy
      - POSTGRES_DB=spy-agency
    ports:
      - '5432:5432'
    restart: always
